spring.application.name=elegance-notification-service

# Configuración de correo (Ejemplo con Gmail, cambiar por tus credenciales reales)
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:gabrielgamer498@gmail.com}
spring.mail.password=${MAIL_PASSWORD:jnkn ieyh mynf xsdz}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Azure AD (OAuth2)
azure.activedirectory.issuer-uri=${AZURE_AD_ISSUER_URI:https://sts.windows.net/7607c5a6-994c-4951-92bc-3af0cf3eb713/}
azure.activedirectory.client-id=${AZURE_AD_CLIENT_ID:api://304d54f7-d485-478a-a1ea-0c2f874b0c1f}
spring.security.oauth2.resourceserver.jwt.issuer-uri=${azure.activedirectory.issuer-uri}

# Puerto del servidor
server.port=8083

# Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html