spring.application.name=elegance-notification-service

# Configuración de correo (Ejemplo con Gmail, cambiar por tus credenciales reales)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=gabrielgamer498@gmail.com
spring.mail.password=jnkn ieyh mynf xsdz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Azure AD (OAuth2)
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://sts.windows.net/7607c5a6-994c-4951-92bc-3af0cf3eb713/

# Puerto del servidor
server.port=8083

# Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html