# Nombre del servicio
spring.application.name=elegance-appointment-service

# Configuración de MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/elegance_appointments?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Configuración de Azure AD (OAuth2)
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://sts.windows.net/7607c5a6-994c-4951-92bc-3af0cf3eb713/

# Puerto del servidor (DIFERENTE al user-service)
server.port=8081

# Configuración de Swagger/OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html